export const SEARCH_BY_PINCODE = "SEARCH_BY_PINCODE";
export const SEARCH_BY_PINCODE_SUCCESS = "SEARCH_BY_PINCODE_SUCCESS";
export const SEARCH_BY_PINCODE_ERROR = "SEARCH_BY_PINCODE_ERROR";

export const SEARCH_BY_POSTOFFICE = "SEARCH_BY_POSTOFFICE";
export const SEARCH_BY_POSTOFFICE_SUCCESS = "SEARCH_BY_POSTOFFICE_SUCCESS";
export const SEARCH_BY_POSTOFFICE_ERROR = "SEARCH_BY_POSTOFFICE_ERROR";

export const SOCIAL_MEDIA_CLICKED = "SOCIAL_MEDIA_CLICKED";
